### ISSUE TITLE
Faster SHA-1 with elm/bytes support

### ISSUE THREAD

**Issue by TSFoster** [rlopzc/elm-hmac-sha1#4]
Hi,

I published a new version of TSFoster/elm-sha1 today, which provides a much faster implementation and elm/bytes support (both thanks to @folkertdev).

I was going to open a PR updating your dependency, but then I realised that the support for elm/bytes has broader (positive) implications about how it is used in your package, so it would be a bit more than just updating `elm.json`.

Basically, before I do the work, would you be open to receive such a pull request?

**Comment by rlopzc** [comment]
Hello,

Yes, I've followed that PR of folkertdev, is very good. And yes, the PR would be nice, I was going to do it soon.

Btw I never ask if I can open PR's I just open them jajaja, thanks for asking!!

**Comment by TSFoster** [comment]
Ah well I was going to just open one, but when I realised there was more to it, I thought I’d check you weren’t already planning or working on something locally!
